### ISSUE TITLE
RuntimeError("Attempted to populate globals twice") appearing a lot in tests

### ISSUE THREAD

**Issue by irl** [wearpants/twiggy#55]
```
I: pybuild base:184: cd /build/python-twiggy-0.4.7/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
test_hijack (tests.test_logging_compat.HijackTest) ... ok
test_restore (tests.test_logging_compat.HijackTest) ... ok
test_basicConfig (tests.test_logging_compat.TestFakeLogger) ... ok
test_exception (tests.test_logging_compat.TestFakeLogger) ... ok
test_isEnabledFor (tests.test_logging_compat.TestFakeLogger) ... ok
test_level (tests.test_logging_compat.TestFakeLogger) ... ok
test_log (tests.test_logging_compat.TestFakeLogger) ... ok
test_log_bad_level (tests.test_logging_compat.TestFakeLogger) ... ok
test_log_exc_info (tests.test_logging_compat.TestFakeLogger) ... ok
test_log_no_exc_info (tests.test_logging_compat.TestFakeLogger) ... ok
test_percent (tests.test_logging_compat.TestFakeLogger) ... ok
test_cache (tests.test_logging_compat.TestGetLogger) ... ok
test_name (tests.test_logging_compat.TestGetLogger) ... ok
test_root (tests.test_logging_compat.TestGetLogger) ... ok
test_format (tests.test_logging_compat.TestLoggingBridge) ... ok
test_sanity (tests.test_logging_compat.TestLoggingBridge) ... No handlers could be found for logger "decoy"
ok
test_iso_time (tests.test_lib.IsoTimeTest) ... ok
test_thread_name (tests.test_lib.ThreadNameTest) ... ok
test_bad_options (tests.test_logger.InternalLoggerTest) ... ok
test_clone (tests.test_logger.InternalLoggerTest) ... ok
test_critical (tests.test_logger.InternalLoggerTest) ... ok
test_debug (tests.test_logger.InternalLoggerTest) ... ok
test_error (tests.test_logger.InternalLoggerTest) ... ok
test_fields (tests.test_logger.InternalLoggerTest) ... ok
test_fields_dict (tests.test_logger.InternalLoggerTest) ... ok
test_info (tests.test_logger.InternalLoggerTest) ... ok
test_logger_min_level (tests.test_logger.InternalLoggerTest) ... ok
test_name (tests.test_logger.InternalLoggerTest) ... ok
test_notice (tests.test_logger.InternalLoggerTest) ... ok
test_options (tests.test_logger.InternalLoggerTest) ... ok
test_trace (tests.test_logger.InternalLoggerTest) ... ok
test_trap_msg (tests.test_logger.InternalLoggerTest) ... ok
test_trap_output (tests.test_logger.InternalLoggerTest) ... ok
test_warning (tests.test_logger.InternalLoggerTest) ... ok
test_bad_options (tests.test_logger.LoggerTestCase) ... ok
test_critical (tests.test_logger.LoggerTestCase) ... ok
test_debug (tests.test_logger.LoggerTestCase) ... ok
test_error (tests.test_logger.LoggerTestCase) ... ok
test_fields (tests.test_logger.LoggerTestCase) ... ok
test_fields_dict (tests.test_logger.LoggerTestCase) ... ok
test_filter_emitters (tests.test_logger.LoggerTestCase) ... ok
test_info (tests.test_logger.LoggerTestCase) ... ok
test_logger_filter (tests.test_logger.LoggerTestCase) ... ok
test_logger_min_level (tests.test_logger.LoggerTestCase) ... ok
test_min_level_emitters (tests.test_logger.LoggerTestCase) ... ok
test_name (tests.test_logger.LoggerTestCase) ... ok
test_no_emitters (tests.test_logger.LoggerTestCase) ... ok
test_notice (tests.test_logger.LoggerTestCase) ... ok
test_options (tests.test_logger.LoggerTestCase) ... ok
test_struct_dict (tests.test_logger.LoggerTestCase) ... ok
test_trace (tests.test_logger.LoggerTestCase) ... ok
test_warning (tests.test_logger.LoggerTestCase) ... ok
test_bad_logger_filter (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_trap_bad_msg (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_trap_filter (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_trap_output (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_line_conversion (tests.test_formats.ConversionsTestCase) ... ok
test_shell_conversion (tests.test_formats.ConversionsTestCase) ... ok
test_basic (tests.test_formats.FormatTestCase) ... ok
test_copy (tests.test_formats.FormatTestCase) ... ok
test_suppress_newline_false (tests.test_formats.FormatTestCase) ... ok
test_suppress_newline_true (tests.test_formats.FormatTestCase) ... ok
test_trace (tests.test_formats.FormatTestCase) ... ok
test_trace_fold (tests.test_formats.FormatTestCase) ... ok
test_integration (tests.test_integration.IntegrationTestCase) ... ERROR
test_convert (tests.test_converter.ConversionTableTestCase) ... ok
test_copy (tests.test_converter.ConversionTableTestCase) ... ok
test_drop (tests.test_converter.ConversionTableTestCase) ... ok
test_duplicate (tests.test_converter.ConversionTableTestCase) ... ok
test_generic (tests.test_converter.ConversionTableTestCase) ... ok
test_get (tests.test_converter.ConversionTableTestCase) ... ok
test_get_all_no_match (tests.test_converter.ConversionTableTestCase) ... ok
test_init_None (tests.test_converter.ConversionTableTestCase) ... ok
test_init_bad (tests.test_converter.ConversionTableTestCase) ... ok
test_init_dict (tests.test_converter.ConversionTableTestCase) ... ok
test_init_simple (tests.test_converter.ConversionTableTestCase) ... ok
test_init_tuple (tests.test_converter.ConversionTableTestCase) ... ok
test_missing (tests.test_converter.ConversionTableTestCase) ... ok
test_repr (tests.test_converter.ConverterTestCase) ... ok
test_drop (tests.test_converter.HelperTestCase) ... ok
test_same_item (tests.test_converter.HelperTestCase) ... ok
test_same_value (tests.test_converter.HelperTestCase) ... ok
test_add_emitters (tests.test_globals.GlobalsTestCase) ... ERROR
test_globals (tests.test_globals.GlobalsTestCase) ... ERROR
test_populate_globals_twice (tests.test_globals.GlobalsTestCase) ... ERROR
test_quick_setup_None (tests.test_globals.GlobalsTestCase) ... ERROR
test_quick_setup_file (tests.test_globals.GlobalsTestCase) ... ERROR
test_quick_setup_stdout (tests.test_globals.GlobalsTestCase) ... ERROR
test_bad_style (tests.test_message.MessageTestCase) ... ok
test_bad_trace (tests.test_message.MessageTestCase) ... ok
test_basic (tests.test_message.MessageTestCase) ... ok
test_braces_alias (tests.test_message.MessageTestCase) ... ok
test_callables (tests.test_message.MessageTestCase) ... ok
test_dollar_alias (tests.test_message.MessageTestCase) ... ok
test_dollar_style (tests.test_message.MessageTestCase) ... ok
test_dollar_style_bad (tests.test_message.MessageTestCase) ... ok
test_empty_format_spec (tests.test_message.MessageTestCase) ... ok
test_level_property (tests.test_message.MessageTestCase) ... ok
test_name_property (tests.test_message.MessageTestCase) ... ok
test_no_args (tests.test_message.MessageTestCase) ... ok
test_no_args_no_kwargs (tests.test_message.MessageTestCase) ... ok
test_no_kwargs (tests.test_message.MessageTestCase) ... ok
test_percent_alias (tests.test_message.MessageTestCase) ... ok
test_percent_style_args (tests.test_message.MessageTestCase) ... ok
test_percent_style_both (tests.test_message.MessageTestCase) ... ok
test_percent_style_kwargs (tests.test_message.MessageTestCase) ... ok
test_suppress_newlines_false (tests.test_message.MessageTestCase) ... ok
test_suppress_newlines_true (tests.test_message.MessageTestCase) ... ok
test_trace_error_with_error (tests.test_message.MessageTestCase) ... ok
test_trace_error_without_error (tests.test_message.MessageTestCase) ... ok
test_trace_tuple (tests.test_message.MessageTestCase) ... ok
test_bad_min_level (tests.test_filters.EmitterTestCase) ... ok
test_filter_property (tests.test_filters.EmitterTestCase) ... ok
test_None (tests.test_filters.MsgFilterTestCase) ... ok
test_bad_arg (tests.test_filters.MsgFilterTestCase) ... ok
test_basestring (tests.test_filters.MsgFilterTestCase) ... ok
test_bool (tests.test_filters.MsgFilterTestCase) ... ok
test_callable (tests.test_filters.MsgFilterTestCase) ... ok
test_list (tests.test_filters.MsgFilterTestCase) ... ok
test_nested_list (tests.test_filters.MsgFilterTestCase) ... ok
test_regex (tests.test_filters.MsgFilterTestCase) ... ok
test_single_list (tests.test_filters.MsgFilterTestCase) ... ok
test_glob_names (tests.test_filters.namesTestCase) ... ok
test_names (tests.test_filters.namesTestCase) ... ok
test_bogus_compare (tests.test_levels.LevelTestCase) ... skipped 'Python 2.x comparisons are insane'
test_bogus_not_equals (tests.test_levels.LevelTestCase) ... ok
test_dict_key (tests.test_levels.LevelTestCase) ... ok
test_display (tests.test_levels.LevelTestCase) ... ok
test_equality (tests.test_levels.LevelTestCase) ... ok
test_greater_than (tests.test_levels.LevelTestCase) ... ok
test_greater_than_equals (tests.test_levels.LevelTestCase) ... ok
test_inequality (tests.test_levels.LevelTestCase) ... ok
test_less_than (tests.test_levels.LevelTestCase) ... ok
test_less_than_equals (tests.test_levels.LevelTestCase) ... ok
test_name2level (tests.test_levels.LevelTestCase) ... ok
test_async (tests.test_outputs.FileOutputTestCase) ... ok
test_async_unlocked (tests.test_outputs.FileOutputTestCase) ... ok
test_sync (tests.test_outputs.FileOutputTestCase) ... ok
test_sync_unlocked (tests.test_outputs.FileOutputTestCase) ... ok
test_list_output (tests.test_outputs.ListOutputTest) ... ok
test_stream_output (tests.test_outputs.StreamOutputTest) ... ok

======================================================================
ERROR: test_bad_logger_filter (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_trap_bad_msg (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_trap_filter (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_trap_output (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_integration (tests.test_integration.IntegrationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_integration.py", line 22, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_add_emitters (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_globals (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_populate_globals_twice (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_quick_setup_None (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_quick_setup_file (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_quick_setup_stdout (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

----------------------------------------------------------------------
Ran 141 tests in 0.031s

FAILED (errors=11, skipped=1)
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=1: cd /build/python-twiggy-0.4.7/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
dh_auto_test: pybuild --test -i python{version} -p 2.7 returned exit code 13
debian/rules:8: recipe for target 'build' failed
make: *** [build] Error 25
I: pybuild base:184: cd /build/python-twiggy-0.4.7/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
test_hijack (tests.test_logging_compat.HijackTest) ... ok
test_restore (tests.test_logging_compat.HijackTest) ... ok
test_basicConfig (tests.test_logging_compat.TestFakeLogger) ... ok
test_exception (tests.test_logging_compat.TestFakeLogger) ... ok
test_isEnabledFor (tests.test_logging_compat.TestFakeLogger) ... ok
test_level (tests.test_logging_compat.TestFakeLogger) ... ok
test_log (tests.test_logging_compat.TestFakeLogger) ... ok
test_log_bad_level (tests.test_logging_compat.TestFakeLogger) ... ok
test_log_exc_info (tests.test_logging_compat.TestFakeLogger) ... ok
test_log_no_exc_info (tests.test_logging_compat.TestFakeLogger) ... ok
test_percent (tests.test_logging_compat.TestFakeLogger) ... ok
test_cache (tests.test_logging_compat.TestGetLogger) ... ok
test_name (tests.test_logging_compat.TestGetLogger) ... ok
test_root (tests.test_logging_compat.TestGetLogger) ... ok
test_format (tests.test_logging_compat.TestLoggingBridge) ... ok
test_sanity (tests.test_logging_compat.TestLoggingBridge) ... No handlers could be found for logger "decoy"
ok
test_iso_time (tests.test_lib.IsoTimeTest) ... ok
test_thread_name (tests.test_lib.ThreadNameTest) ... ok
test_bad_options (tests.test_logger.InternalLoggerTest) ... ok
test_clone (tests.test_logger.InternalLoggerTest) ... ok
test_critical (tests.test_logger.InternalLoggerTest) ... ok
test_debug (tests.test_logger.InternalLoggerTest) ... ok
test_error (tests.test_logger.InternalLoggerTest) ... ok
test_fields (tests.test_logger.InternalLoggerTest) ... ok
test_fields_dict (tests.test_logger.InternalLoggerTest) ... ok
test_info (tests.test_logger.InternalLoggerTest) ... ok
test_logger_min_level (tests.test_logger.InternalLoggerTest) ... ok
test_name (tests.test_logger.InternalLoggerTest) ... ok
test_notice (tests.test_logger.InternalLoggerTest) ... ok
test_options (tests.test_logger.InternalLoggerTest) ... ok
test_trace (tests.test_logger.InternalLoggerTest) ... ok
test_trap_msg (tests.test_logger.InternalLoggerTest) ... ok
test_trap_output (tests.test_logger.InternalLoggerTest) ... ok
test_warning (tests.test_logger.InternalLoggerTest) ... ok
test_bad_options (tests.test_logger.LoggerTestCase) ... ok
test_critical (tests.test_logger.LoggerTestCase) ... ok
test_debug (tests.test_logger.LoggerTestCase) ... ok
test_error (tests.test_logger.LoggerTestCase) ... ok
test_fields (tests.test_logger.LoggerTestCase) ... ok
test_fields_dict (tests.test_logger.LoggerTestCase) ... ok
test_filter_emitters (tests.test_logger.LoggerTestCase) ... ok
test_info (tests.test_logger.LoggerTestCase) ... ok
test_logger_filter (tests.test_logger.LoggerTestCase) ... ok
test_logger_min_level (tests.test_logger.LoggerTestCase) ... ok
test_min_level_emitters (tests.test_logger.LoggerTestCase) ... ok
test_name (tests.test_logger.LoggerTestCase) ... ok
test_no_emitters (tests.test_logger.LoggerTestCase) ... ok
test_notice (tests.test_logger.LoggerTestCase) ... ok
test_options (tests.test_logger.LoggerTestCase) ... ok
test_struct_dict (tests.test_logger.LoggerTestCase) ... ok
test_trace (tests.test_logger.LoggerTestCase) ... ok
test_warning (tests.test_logger.LoggerTestCase) ... ok
test_bad_logger_filter (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_trap_bad_msg (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_trap_filter (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_trap_output (tests.test_logger.LoggerTrapTestCase) ... ERROR
test_line_conversion (tests.test_formats.ConversionsTestCase) ... ok
test_shell_conversion (tests.test_formats.ConversionsTestCase) ... ok
test_basic (tests.test_formats.FormatTestCase) ... ok
test_copy (tests.test_formats.FormatTestCase) ... ok
test_suppress_newline_false (tests.test_formats.FormatTestCase) ... ok
test_suppress_newline_true (tests.test_formats.FormatTestCase) ... ok
test_trace (tests.test_formats.FormatTestCase) ... ok
test_trace_fold (tests.test_formats.FormatTestCase) ... ok
test_integration (tests.test_integration.IntegrationTestCase) ... ERROR
test_convert (tests.test_converter.ConversionTableTestCase) ... ok
test_copy (tests.test_converter.ConversionTableTestCase) ... ok
test_drop (tests.test_converter.ConversionTableTestCase) ... ok
test_duplicate (tests.test_converter.ConversionTableTestCase) ... ok
test_generic (tests.test_converter.ConversionTableTestCase) ... ok
test_get (tests.test_converter.ConversionTableTestCase) ... ok
test_get_all_no_match (tests.test_converter.ConversionTableTestCase) ... ok
test_init_None (tests.test_converter.ConversionTableTestCase) ... ok
test_init_bad (tests.test_converter.ConversionTableTestCase) ... ok
test_init_dict (tests.test_converter.ConversionTableTestCase) ... ok
test_init_simple (tests.test_converter.ConversionTableTestCase) ... ok
test_init_tuple (tests.test_converter.ConversionTableTestCase) ... ok
test_missing (tests.test_converter.ConversionTableTestCase) ... ok
test_repr (tests.test_converter.ConverterTestCase) ... ok
test_drop (tests.test_converter.HelperTestCase) ... ok
test_same_item (tests.test_converter.HelperTestCase) ... ok
test_same_value (tests.test_converter.HelperTestCase) ... ok
test_add_emitters (tests.test_globals.GlobalsTestCase) ... ERROR
test_globals (tests.test_globals.GlobalsTestCase) ... ERROR
test_populate_globals_twice (tests.test_globals.GlobalsTestCase) ... ERROR
test_quick_setup_None (tests.test_globals.GlobalsTestCase) ... ERROR
test_quick_setup_file (tests.test_globals.GlobalsTestCase) ... ERROR
test_quick_setup_stdout (tests.test_globals.GlobalsTestCase) ... ERROR
test_bad_style (tests.test_message.MessageTestCase) ... ok
test_bad_trace (tests.test_message.MessageTestCase) ... ok
test_basic (tests.test_message.MessageTestCase) ... ok
test_braces_alias (tests.test_message.MessageTestCase) ... ok
test_callables (tests.test_message.MessageTestCase) ... ok
test_dollar_alias (tests.test_message.MessageTestCase) ... ok
test_dollar_style (tests.test_message.MessageTestCase) ... ok
test_dollar_style_bad (tests.test_message.MessageTestCase) ... ok
test_empty_format_spec (tests.test_message.MessageTestCase) ... ok
test_level_property (tests.test_message.MessageTestCase) ... ok
test_name_property (tests.test_message.MessageTestCase) ... ok
test_no_args (tests.test_message.MessageTestCase) ... ok
test_no_args_no_kwargs (tests.test_message.MessageTestCase) ... ok
test_no_kwargs (tests.test_message.MessageTestCase) ... ok
test_percent_alias (tests.test_message.MessageTestCase) ... ok
test_percent_style_args (tests.test_message.MessageTestCase) ... ok
test_percent_style_both (tests.test_message.MessageTestCase) ... ok
test_percent_style_kwargs (tests.test_message.MessageTestCase) ... ok
test_suppress_newlines_false (tests.test_message.MessageTestCase) ... ok
test_suppress_newlines_true (tests.test_message.MessageTestCase) ... ok
test_trace_error_with_error (tests.test_message.MessageTestCase) ... ok
test_trace_error_without_error (tests.test_message.MessageTestCase) ... ok
test_trace_tuple (tests.test_message.MessageTestCase) ... ok
test_bad_min_level (tests.test_filters.EmitterTestCase) ... ok
test_filter_property (tests.test_filters.EmitterTestCase) ... ok
test_None (tests.test_filters.MsgFilterTestCase) ... ok
test_bad_arg (tests.test_filters.MsgFilterTestCase) ... ok
test_basestring (tests.test_filters.MsgFilterTestCase) ... ok
test_bool (tests.test_filters.MsgFilterTestCase) ... ok
test_callable (tests.test_filters.MsgFilterTestCase) ... ok
test_list (tests.test_filters.MsgFilterTestCase) ... ok
test_nested_list (tests.test_filters.MsgFilterTestCase) ... ok
test_regex (tests.test_filters.MsgFilterTestCase) ... ok
test_single_list (tests.test_filters.MsgFilterTestCase) ... ok
test_glob_names (tests.test_filters.namesTestCase) ... ok
test_names (tests.test_filters.namesTestCase) ... ok
test_bogus_compare (tests.test_levels.LevelTestCase) ... skipped 'Python 2.x comparisons are insane'
test_bogus_not_equals (tests.test_levels.LevelTestCase) ... ok
test_dict_key (tests.test_levels.LevelTestCase) ... ok
test_display (tests.test_levels.LevelTestCase) ... ok
test_equality (tests.test_levels.LevelTestCase) ... ok
test_greater_than (tests.test_levels.LevelTestCase) ... ok
test_greater_than_equals (tests.test_levels.LevelTestCase) ... ok
test_inequality (tests.test_levels.LevelTestCase) ... ok
test_less_than (tests.test_levels.LevelTestCase) ... ok
test_less_than_equals (tests.test_levels.LevelTestCase) ... ok
test_name2level (tests.test_levels.LevelTestCase) ... ok
test_async (tests.test_outputs.FileOutputTestCase) ... ok
test_async_unlocked (tests.test_outputs.FileOutputTestCase) ... ok
test_sync (tests.test_outputs.FileOutputTestCase) ... ok
test_sync_unlocked (tests.test_outputs.FileOutputTestCase) ... ok
test_list_output (tests.test_outputs.ListOutputTest) ... ok
test_stream_output (tests.test_outputs.StreamOutputTest) ... ok

======================================================================
ERROR: test_bad_logger_filter (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_trap_bad_msg (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_trap_filter (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_trap_output (tests.test_logger.LoggerTrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_logger.py", line 249, in setUp
    _twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_integration (tests.test_integration.IntegrationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_integration.py", line 22, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_add_emitters (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_globals (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_populate_globals_twice (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_quick_setup_None (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_quick_setup_file (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

======================================================================
ERROR: test_quick_setup_stdout (tests.test_globals.GlobalsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_globals.py", line 19, in setUp
    twiggy._populate_globals()
  File "twiggy/__init__.py", line 23, in _populate_globals
    raise RuntimeError("Attempted to populate globals twice")
RuntimeError: Attempted to populate globals twice

----------------------------------------------------------------------
Ran 141 tests in 0.031s

FAILED (errors=11, skipped=1)
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=1: cd /build/python-twiggy-0.4.7/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
dh_auto_test: pybuild --test -i python{version} -p 2.7 returned exit code 13
debian/rules:8: recipe for target 'build' failed
make: *** [build] Error 25

```

**Comment by irl** [comment]
This is due to TWIGGY_UNDER_TEST not being set as an environment variable. I'm sure this was probably documented somewhere but I just failed to read it.
