### ISSUE TITLE
Unicode internals are dicey

### ISSUE THREAD

**Issue by wearpants** [wearpants/twiggy#9]
when log.field(name=u'中').info() , error message as below
WARNING:twiggy.internal:Error outputting with <twiggy.outputs.StreamOutput object at 0x02E65410>. Message: <twiggy.message.Message object at 0x02E61AD0> TRACE Traceback (most recent call last): TRACE File "D:\program\Python27\lib\site-packages\twiggy\logger.py", line 260, in _emit TRACE o.output(msg) TRACE File "D:\program\Python27\lib\site-packages\twiggy\outputs.py", line 54, in sync_output_locked TRACE x = self._format(msg) TRACE File "D:\program\Python27\lib\site-packages\twiggy\formats.py", line 34, in call TRACE fields = self.format_fields(msg) TRACE File "D:\program\Python27\lib\site-packages\twiggy\formats.py", line 58, in format_fields TRACE return self.conversion.convert(msg.fields) TRACE File "D:\program\Python27\lib\site-packages\twiggy\lib\converter.py", line 82, in convert TRACE item = c.convertItem(c.key, c.convertValue(d[c.key])) TRACE UnicodeEncodeError: 'ascii' codec can't encode character u'\u4e2d' in position 0: ordinal not in range(128)

Imported from Bitbucket.

**Comment by abadger** [comment]
Analyzed this a little.  This is a problem for all of name(), fields(), and info()/warning()/debug()/etc.  I can make the problem go away on python2 by changing this:

``` python
 line_conversion = ConversionTable([
 [...]
-    ('name', str, '{1}'.format),
+    ('name', to_bytes, '{1}'.format),
 ])
```

to_bytes is fromfrom kitchen.text.converters import to_bytes... how it works isn't important right now.. I'll have to reimplement from scratch if we need something like it in twiggy (it's license is lgpl2+).  What it does is convert any string into a byte string using the utf-8 encoding.

This works on python2 because native strings (string literals with no initial marking ex: "test") are byte strings but will behave oddly on python3 for two reasons: string literals are text strings and new-style format strings only work with text strings, not with byte strings.

To fix this on both python2 and python3 we'll probably have to convert all strings to text strings when they enter twiggy's control and then convert back to byte strings just before we output the strings to the console/log/etc.

**Comment by wearpants** [comment]
Happy to use your tools from Kitchen for unicode issues.

Re: license - I'd like to get this in the standard library eventually, but I think it's premature to reinvent wheels b/c of licensing issues or to avoid external dependencies... so let's just go with it ^_^

**Comment by abadger** [comment]
Cool.  I also had to rewrite those functions from scratch to be BSD licensed once for Ansible (Most of Ansible is GPLv3+ but we have some helper utilities for people writing Ansible modules.  Those are BSD licensed.)  So I can copy those into the code if we want to avoid the external dependency in the future.

**Comment by abadger** [comment]
Another note: With the present code, unicode appears to work fine with Python3.  It's only on Python2 that this is failing.
